// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UtilityBillingApplicationMVC.Models;

public partial class BillHistories
{
    public int BillId { get; set; }

    public int UserId { get; set; }

    public int MeterId { get; set; }

    public decimal MeterReading { get; set; }

    public DateTime BillingDate { get; set; }

    public decimal BillAmount { get; set; }

    public string Status { get; set; }

    public virtual MeterInfos Meter { get; set; }

    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    public virtual Users User { get; set; }
}