// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UtilityBillingApplicationMVC.Models;

public partial class MeterInfos
{
    public int MeterId { get; set; }

    public int UserId { get; set; }

    public string RequiredLoad { get; set; }

    public string ConnectionType { get; set; }

    public int? ApplicationStatusId { get; set; }

    public virtual ApplicationStatuses ApplicationStatus { get; set; }

    public virtual ICollection<BillHistories> BillHistories { get; set; } = new List<BillHistories>();

    public virtual Users User { get; set; }
}