// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UtilityBillingApplicationMVC.Models;

public partial class Tickets
{
    public int TicketId { get; set; }

    public int? UserId { get; set; }

    public DateTime TicketDate { get; set; }

    public string TicketDescription { get; set; }

    public string Status { get; set; }

    public string TicketSubject { get; set; }

    public virtual Users User { get; set; }
}